import assert from "node:assert/strict";
import { createInitialSession, advanceSimulation, submitSurvey } from "../shared/simulation.js";
import { initializeSurveys, checkMidpoint, openSurvey, surveyCompleteForGame } from "../shared/surveys.js";
import { questionsForCheckpoint, scoredResponse, BASELINE_QUESTIONS, MDMT_QUESTIONS, SURVEY_QUESTIONS, validateResponses } from "../shared/survey-config.js";

const answers = (checkpoint, value) => Object.fromEntries(questionsForCheckpoint(checkpoint).map((q) => [q.id, value ?? String(q.min)]));
assert.equal(SURVEY_QUESTIONS.length, 20);
assert.equal(MDMT_QUESTIONS.length, 16);
assert.equal(BASELINE_QUESTIONS.length, 6);
assert.equal(scoredResponse(BASELINE_QUESTIONS[3], "1"), 5);
assert.equal(scoredResponse(BASELINE_QUESTIONS[3], "5"), 1);
assert.equal(scoredResponse(MDMT_QUESTIONS[0], "does_not_fit"), null);
assert.equal(scoredResponse(MDMT_QUESTIONS[0], "0"), 0);
for (const bad of ["", null, false, "8", "-1", "3.5"]) {
  const data = answers("midpoint"); data[MDMT_QUESTIONS[0].id] = bad;
  assert.throws(() => validateResponses("midpoint", data));
}
const notFit = answers("midpoint");
for (const question of MDMT_QUESTIONS) notFit[question.id] = "does_not_fit";
validateResponses("midpoint", notFit);
assert.throws(() => validateResponses("baseline", {}));
const state = createInitialSession("survey-test", { gameNumber: 1 });
initializeSurveys(state);
assert.equal(state.survey.checkpoint, "baseline");
advanceSimulation(state, Date.now() + 60000);
assert.equal(state.tick, 0, "Baseline freezes simulation");
assert.equal(state.mission.remainingSeconds, 1800);
submitSurvey(state, answers("baseline"));
assert.equal(state.paused, false);
assert.equal(state.survey.completed, false);
const half = Math.ceil(state.survey.initialFireKeys.length / 2);
const original = [...state.fires];
state.extinguished = original.slice(0, half).map((fire) => ({ ...fire, kind: "firebreak" }));
checkMidpoint(state);
assert.equal(state.survey.active, false, "Firebreak geometry is not extinguished wildfire");
state.extinguished = original.slice(0, half - 1).map((fire) => ({ ...fire, kind: "water" }));
checkMidpoint(state);
assert.equal(state.survey.active, false, "Below half does not trigger");
state.extinguished.push({ ...original[half - 1], kind: "water" });
checkMidpoint(state);
assert.equal(state.survey.checkpoint, "midpoint");
assert.equal(state.survey.trigger, "half_initial_fires_extinguished");
const pausedTick = state.tick;
advanceSimulation(state, Date.now() + 120000);
assert.equal(state.tick, pausedTick);
submitSurvey(state, notFit);
checkMidpoint(state);
assert.equal(state.survey.active, false, "Midpoint cannot repeat");
state.mission.elapsedSeconds = 1799; state.mission.remainingSeconds = 1; state.mission.deadlineAt = null;
advanceSimulation(state, Date.now());
assert.equal(state.survey.checkpoint, "final");
submitSurvey(state, answers("final"));
assert.equal(surveyCompleteForGame(state), true);
assert.equal(Object.keys(state.survey.history).length, 3);
assert.equal(state.survey.history.midpoint.responses.mdmt_helicopter_reliable, "does_not_fit");
assert.equal(state.survey.history.final.responses.mdmt_helicopter_reliable, "0");
const fallback = createInitialSession("fallback", { gameNumber: 2 });
initializeSurveys(fallback);
fallback.mission.elapsedSeconds = 899;
checkMidpoint(fallback);
assert.equal(fallback.survey.active, false);
fallback.mission.elapsedSeconds = 900;
checkMidpoint(fallback);
assert.equal(fallback.survey.trigger, "15_minute_fallback");
submitSurvey(fallback, answers("midpoint"));
assert.equal(fallback.survey.history.baseline, undefined);
assert.equal(openSurvey(fallback, "midpoint"), false);
console.log("Survey checks passed: exact items/scales, zero/Does Not Fit, reverse coding, baseline once, fire threshold, 15-minute fallback, pause and separate records.");
